apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: All applications are part of this project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"

  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
