{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-{{ .name }}
  namespace: argocd
spec:
  project: applications
  source:
    repoURL: '{{ .repoUrl }}'
    path: {{ .repoPath }}
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app-{{ .namespace }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
{{- end }}