apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application-bundle
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: argocd
    server: "https://kubernetes.default.svc"
  source:
    path: applications
    repoURL: "https://github.com/Deofex/k8s-democluster"
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
