apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-applications
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/Deofex/k8s-democluster'
    path: customerapplicatons
    targetRevision: HEAD
    helm:
      valueFiles:
      - $values/apps/values.yaml
  - repoURL: 'https://github.com/Deofex/testrepo'
    path: apps
    targetRevision: HEAD
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
