apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloack-http-route
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Deofex/k8s-democluster'
    path: keycloack
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
