apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-nginx-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Deofex/k8s-democluster'
    path: argocd/gateway
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
