apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-shared-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Deofex/k8s-democluster'
    path: nginx-shared-gateway
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx-shared-gateway
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
