apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric
  namespace: argocd
spec:

  project: default

  source:
    repoURL: "ghcr.io/nginxinc/charts/nginx-gateway-fabric"
    targetRevision: 1.3.0
    helm:
      values: |
        service:
          type: NodePort
          ports:
            - port: 80
              targetPort: 80
              nodePort: 30080
              protocol: TCP
              name: http
            - port: 443
              targetPort: 443
              nodePort: 30443
              protocol: TCP
              name: https

  destination:
    namespace: nginx-gateway
    server: "https://kubernetes.default.svc"

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
