apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-shared-gateway
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - hostname: argocd.local
      name: argocd-https
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: argocd-server-tls
